# Draws a snowman in python turtle
# by Laura Lang 12/21/2023 for Joy of Coding Turtle Portfolio

import turtle

turtle.Screen().bgcolor("blue")
turtle.speed(0)
turtle.penup()
turtle.goto(-100, 40)
turtle.pendown()

def snowman():
  snowman_outline()
  snowman_black_items()
  carrot_nose()
  snowman_red_items()
  flower()
  

def snowman_outline():
  turtle.color("white")
  turtle.begin_fill()
  turtle.circle(30)
  turtle.end_fill()
  turtle.right(90)
  turtle.forward(72)
  turtle.left(90)
  turtle.begin_fill()
  turtle.circle(40)
  turtle.end_fill()
  turtle.right(90)
  turtle.forward(97)
  turtle.left(90)
  turtle.begin_fill()
  turtle.circle(50)
  turtle.end_fill()
 
def rectangle(color, length, width):
  turtle.color(color)
  for x in range(2):
    turtle.forward(length)
    turtle.right(90)
    turtle.forward(width)
    turtle.right(90) 
  
def snowman_black_items():
  turtle.penup()
  turtle.left(90)
  turtle.forward(115)
  turtle.right(90)
  for button in range(3):
    turtle.pendown()
    turtle.color("black")
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.left(90)
    turtle.forward(15)
    turtle.right(90)
  turtle.left(90)
  turtle.forward(70)
  turtle.right(90)
  turtle.forward(-40)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  rectangle("black", 80, 10)
  turtle.end_fill()
  turtle.penup()
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(35)
  turtle.right(90)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  rectangle("black", 40, 35)
  turtle.end_fill()
  turtle.penup()
  turtle.right(90)
  turtle.forward(70)
  turtle.left(90)
  turtle.forward(10)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  turtle.circle(5)
  turtle.end_fill()
  turtle.penup()
  turtle.forward(18)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  turtle.circle(5)
  turtle.end_fill()
  turtle.penup()
  
def carrot_nose():
  turtle.forward(-9)
  turtle.right(90)
  turtle.forward(7)
  turtle.pendown()
  turtle.color("orange")
  turtle.begin_fill()
  turtle.forward(5)
  turtle.left(100)
  turtle.forward(25)
  turtle.left(155)
  turtle.forward(25)
  turtle.end_fill()
  turtle.penup()
 
def snowman_red_items():
  turtle.left(115)
  turtle.forward(15)
  turtle.left(90)
  turtle.forward(-30)
  turtle.pendown()
  turtle.color("red")
  turtle.begin_fill()
  rectangle("red", 50, 15)
  turtle.forward(15)
  turtle.left(225)
  rectangle("red", 70, 15 )
  turtle.end_fill()
  turtle.penup()
  
def flower():
  turtle.pendown()
  turtle.forward(10)
  turtle.right(45)
  turtle.forward(3)
  turtle.color("yellow")
  #turtle.begin_fill()
  for petals in range(8):
    turtle.circle(8)
    turtle.left(45)
  turtle.penup()
  turtle.right(95)
  turtle.forward(63)
  turtle.right(90)
  turtle.forward(40)
  turtle.pendown()
  turtle.color("yellow")
  for petals in range(8):
    turtle.circle(5)
    turtle.left(45)
  turtle.penup()
  turtle.hideturtle()
